server:
  port: 8500
spring:
  application:
    name: gateway
  cloud:
    gateway:
     routes:
      - id: borrow-service
        uri: lb://borrowservice
        predicates:
        - Path=/borrow/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka01:8801/eureka,http://eureka02:8802/eureka